### ISSUE TITLE
Dot not syn data

### ISSUE THREAD

**Issue by truongtrau** [APshenkin/omnilayer-explorer-docker#1]
Dear sir @APshenkin,
I had ran docker-compose result status done all
But seem it's do not Syn data from chain, you can see sceenshot 
Could you help me this issues 
Thank you so much!
![image](https://user-images.githubusercontent.com/22745195/57613644-974b7500-75a1-11e9-9d2d-0a44d155cbbb.png)

**Comment by APshenkin** [comment]
@truongtrau 
Hi!

Omnicore node need time to sync. Omni tokens txs starts from 252317 block. So you will not see any txs before omnicore sync to 252317 in mainnet.

you can check current block in logs:

```
docker exec -ti compose_omni_core_1 /bin/bash
cd /root/.bitcoin
tail -f debug.log
```

**Comment by truongtrau** [comment]
Hi!
May I ask? 
1. Current config is right mainnet 
2. Now I want to know It is still working (docker logs sceenshot)
3. I can't check 
> docker exec -ti compose_omni_core_1 /bin/bash
> cd /root/.bitcoin
> tail -f debug.log
> 
Thank so lot !
![image](https://user-images.githubusercontent.com/22745195/57670142-299e5800-7638-11e9-9246-82b5d057b719.png)

**Comment by truongtrau** [comment]
Hi @APshenkin 
I still worry when logs "Current block is  None"    
Could you help me!
Thank so lot!

**Comment by truongtrau** [comment]
Because Limit resouces
